Repository sun-mart-egg/funding-gift-backend, pull requests merged in 2025-02, with the labels that each got.

#9 [Chore] aop를 통한 service 매서드 실행 시간 측정 로깅
  BE/src/main/java/com/d201/fundingift/_common/aop/ExecutionTimeAspect.java
Labels: feat

#10 [Refactor] funding post test 코드 개선
  BE/src/main/resources/application.yml
  BE/src/test/java/com/d201/fundingift/medium/funding/service/FundingPostServiceTest.java
  BE/src/test/resources/sql/delete-all-data.sql
  BE/src/test/resources/sql/post-funding-test-data.sql
Labels: refactor, chore

#8 [Feat] 로그인 트랜잭션 최적화 및 Refresh Token 로직 추가
  BE/src/main/java/com/d201/fundingift/_common/config/SecurityConfig.java
  BE/src/main/java/com/d201/fundingift/_common/jwt/JwtAuthorizationFilter.java
  BE/src/main/java/com/d201/fundingift/_common/jwt/JwtRepository.java
  BE/src/main/java/com/d201/fundingift/_common/jwt/JwtUtil.java
  BE/src/main/java/com/d201/fundingift/_common/jwt/RedisJwtRepository.java
  BE/src/main/java/com/d201/fundingift/_common/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  BE/src/main/java/com/d201/fundingift/consumer/controller/ConsumerController.java
  BE/src/main/java/com/d201/fundingift/consumer/service/ConsumerService.java
Labels: bug, refactor, feat
