Repository sun-mart-egg/funding-gift-backend, pull requests merged in 2025-01, with the labels that each got.

#3 [Feat] 로그인 시 프로필 업데이트
  BE/src/main/java/com/d201/fundingift/_common/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
Labels: feat

#4 [Feat] 친구 도메인 리팩토링
  .gitignore
  BE/src/main/java/com/d201/fundingift/_common/config/RedisConfig.java
  BE/src/main/java/com/d201/fundingift/_common/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  BE/src/main/java/com/d201/fundingift/_common/response/ErrorType.java
  BE/src/main/java/com/d201/fundingift/attendance/service/AttendanceService.java
  BE/src/main/java/com/d201/fundingift/friend/controller/FriendController.java
  BE/src/main/java/com/d201/fundingift/friend/domain/Friend.java
  BE/src/main/java/com/d201/fundingift/friend/domain/port/FriendExternalPort.java
  BE/src/main/java/com/d201/fundingift/friend/domain/port/FriendRepository.java
  BE/src/main/java/com/d201/fundingift/friend/dto/FriendDto.java
  BE/src/main/java/com/d201/fundingift/friend/dto/GetFriendCommand.java
  BE/src/main/java/com/d201/fundingift/friend/dto/response/GetFriendsResponse.java
  BE/src/main/java/com/d201/fundingift/friend/dto/response/GetKakaoFriendsResponse.java
  BE/src/main/java/com/d201/fundingift/friend/entity/Friend.java
  BE/src/main/java/com/d201/fundingift/friend/infrastructure/entity/FriendEntity.java
  BE/src/main/java/com/d201/fundingift/friend/infrastructure/external/KakaoFriendClient.java
  BE/src/main/java/com/d201/fundingift/friend/infrastructure/repository/FriendJPARepository.java
  BE/src/main/java/com/d201/fundingift/friend/infrastructure/repository/FriendRepositoryImpl.java
  BE/src/main/java/com/d201/fundingift/friend/repository/FriendRepository.java
  BE/src/main/java/com/d201/fundingift/friend/service/FriendService.java
  BE/src/main/java/com/d201/fundingift/funding/controller/FundingController.java
  BE/src/main/java/com/d201/fundingift/funding/service/FundingService.java
Labels: bug, refactor, delete

#5 [Refactor] 핸들러 로직 리팩토링
  BE/src/main/java/com/d201/fundingift/_common/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  BE/src/main/java/com/d201/fundingift/consumer/service/ConsumerService.java
Labels: refactor

#6 [Refactor] 상품 로직 리팩토링
  BE/src/main/java/com/d201/fundingift/funding/repository/FundingRepository.java
  BE/src/main/java/com/d201/fundingift/product/entity/ProductCategory.java
  BE/src/main/java/com/d201/fundingift/product/repository/ProductOptionRepository.java
  BE/src/main/java/com/d201/fundingift/product/repository/ProductRepository.java
  BE/src/main/java/com/d201/fundingift/product/service/ProductService.java
Labels: refactor
